name: SonarQube Analysis
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install dependencies (Gradle example)
        run: ./gradlew build
      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=<YOUR_PROJECT_KEY> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=<YOUR_ORG> \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Upload Quality Gate Status (Optional)
        run: echo "SonarQube Quality Gate Check Complete"
